package com.company;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import javax.swing.*;

/**
 *
 * @author randkill
 */
public class SignUpPage extends javax.swing.JFrame {

    String username=null;
    char[] password=null;
    String passwordSt =null;
    char[] repassword=null;
    char[] passwordHint=null;
    String passwordHintString;
    boolean permission = false;

    /**
     * Creates new form SignUpPage
     */
    public SignUpPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        usernameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        renterpasswordLabel = new javax.swing.JLabel();
        passwordHintLabel = new javax.swing.JLabel();
        userNameTextField = new javax.swing.JTextField();
        passwordTextField = new javax.swing.JPasswordField();
        renterPasswordTextField = new javax.swing.JPasswordField();
        passwordHintTextField = new javax.swing.JPasswordField();
        YesButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        NoButton = new javax.swing.JButton();
        signUpButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        usernameLabel.setText("username :");

        passwordLabel.setText("password :");

        renterpasswordLabel.setText("renter password :");

        passwordHintLabel.setText("password-hint :");

        userNameTextField.setText("username");
        userNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameTextFieldActionPerformed(evt);
            }
        });

        passwordTextField.setText("jPasswordField1");
        passwordTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordTextFieldActionPerformed(evt);
            }
        });

        renterPasswordTextField.setText("jPasswordField2");
        renterPasswordTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                renterPasswordTextFieldActionPerformed(evt);
            }
        });

        passwordHintTextField.setText("jPasswordField3");
        passwordHintTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordHintTextFieldActionPerformed(evt);
            }
        });

        YesButton.setText("yes");
        YesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YesButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("Are you sure ?");

        NoButton.setText("no");
        NoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoButtonActionPerformed(evt);
            }
        });

        signUpButton.setText("sign up");
        signUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpButtonActionPerformed(evt);
            }
        });

        backButton.setText("back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel5)
                                        .addComponent(passwordHintLabel)
                                        .addComponent(renterpasswordLabel)
                                        .addComponent(passwordLabel)
                                        .addComponent(usernameLabel))
                                .addGap(55, 55, 55)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(userNameTextField)
                                                .addComponent(passwordTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                                                .addComponent(renterPasswordTextField)
                                                .addComponent(passwordHintTextField))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(YesButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(NoButton)))
                                .addContainerGap(134, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(backButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(signUpButton)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(usernameLabel)
                                        .addComponent(userNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(passwordLabel)
                                        .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(renterpasswordLabel)
                                        .addComponent(renterPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(passwordHintLabel)
                                        .addComponent(passwordHintTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5)
                                        .addComponent(YesButton)
                                        .addComponent(NoButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(signUpButton)
                                        .addComponent(backButton))
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>

    private void YesButtonActionPerformed(java.awt.event.ActionEvent evt) {
        permission = true;
    }

    private void NoButtonActionPerformed(java.awt.event.ActionEvent evt) {
        permission = false;
    }

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {
        setVisible(false);
    }

    private void signUpButtonActionPerformed(java.awt.event.ActionEvent evt) {
        username = userNameTextField.getText();
        passwordTextField.getPassword();
        this.password = passwordTextField.getPassword();
        passwordSt = new String(password);
        renterPasswordTextField.getPassword();
        this.repassword = renterPasswordTextField.getPassword();
        passwordHintTextField.getPassword();
        this.passwordHint = passwordHintTextField.getPassword();
        passwordHintString = new String(passwordHint);
        creatAccount();
        setVisible(false);
    }

    private void userNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {
        userNameTextField.getText();
        username = userNameTextField.getText();
    }

    private void passwordTextFieldActionPerformed(java.awt.event.ActionEvent evt) {
        passwordTextField.getPassword();
        this.password = passwordTextField.getPassword();
        passwordSt = new String(password);
    }

    private void renterPasswordTextFieldActionPerformed(java.awt.event.ActionEvent evt) {
        renterPasswordTextField.getPassword();
        this.repassword = renterPasswordTextField.getPassword();


    }

    private void passwordHintTextFieldActionPerformed(java.awt.event.ActionEvent evt) {
        passwordHintTextField.getPassword();
        this.passwordHint = passwordHintTextField.getPassword();
        passwordHintString = new String(passwordHint);
    }
    public void creatAccount()
    {
        if(username == null)
        {
            JOptionPane.showMessageDialog(null , "username field is empty !");
        }
        if(password == null)
        {
            JOptionPane.showMessageDialog(null ,"password field is empty !");
        }
        if(repassword == null)
        {
            JOptionPane.showMessageDialog(null , "renter-password field is empty !");
        }
        if(passwordHint ==null)
        {
            JOptionPane.showMessageDialog(null , "password-hint field is empty !");
        }
        if(password.equals(repassword))
        {
            JOptionPane.showMessageDialog(null , "password and repassword are not the same !");
        }
        if(permission == true)
        {
            Account account = new Account(username , passwordSt  , passwordHintString);
            //JOptionPane.showMessageDialog(null , account.toString());
            try {
                FileW creator = new FileW(account.toString(), username);
                creator.writeFile();
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null , e);;
            }
            setVisible(false);
        }
        else
        {
            JOptionPane.showMessageDialog(null , "Enter yes to let application creat account !");
        }

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUpPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUpPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUpPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUpPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUpPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton NoButton;
    private javax.swing.JButton YesButton;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel passwordHintLabel;
    private javax.swing.JPasswordField passwordHintTextField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPasswordField passwordTextField;
    private javax.swing.JPasswordField renterPasswordTextField;
    private javax.swing.JLabel renterpasswordLabel;
    private javax.swing.JButton signUpButton;
    private javax.swing.JTextField userNameTextField;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration
}
