package com.company;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import com.company.AudioWindow;
import com.company.PhotoWindows;
import com.company.VideoWindow;

import javax.swing.*;
import java.awt.event.ActionEvent;

/**
 *
 * @author randkill
 */
public class WelcomePage extends javax.swing.JFrame {

    public boolean accountstatus;
    public void checkAccount()
    {
        if(accountstatus == true)
        {
            nSignedin.setVisible(false);
            Signedin.setVisible(true);
        }
        else
        {
            nSignedin.setVisible(true);
            Signedin.setVisible(false);
        }
    }



    /**
     * Creates new form WelcomePage
     */
    public WelcomePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jMenu11 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Signedin = new javax.swing.JLabel();
        nSignedin = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu12 = new javax.swing.JMenu();
        newMenu = new javax.swing.JMenu();
        videoMenu = new javax.swing.JMenuItem();
        audioMenu = new javax.swing.JMenuItem();
        photoMenu = new javax.swing.JMenuItem();
        documentMenu = new javax.swing.JMenuItem();
        openMenu = new javax.swing.JMenuItem();
        aboutMenu = new javax.swing.JMenuItem();
        exitMenu = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        signInMenu = new javax.swing.JMenuItem();
        signUpMenu = new javax.swing.JMenuItem();
        signOutMenu = new javax.swing.JMenuItem();

        jMenu11.setText("jMenu11");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Sign in to use this application otherwise , creat an account");

        jLabel2.setText("Welcome to DataFile Editor");

        Signedin.setText("You are signed in");

        nSignedin.setText("You are not signed in");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(nSignedin)
                                        .addComponent(Signedin)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel2))
                                .addContainerGap(169, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(Signedin)
                                .addGap(18, 18, 18)
                                .addComponent(nSignedin)
                                .addContainerGap(185, Short.MAX_VALUE))
        );

        jMenu12.setText("File");
        jMenu12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu12ActionPerformed(evt);
            }
        });

        newMenu.setText("new");

        videoMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        videoMenu.setText("video");
        videoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                videoMenuActionPerformed(evt);
            }
        });
        newMenu.add(videoMenu);

        audioMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        audioMenu.setText("audio");
        audioMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                audioMenuActionPerformed(evt);
            }
        });
        newMenu.add(audioMenu);

        photoMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        photoMenu.setText("photo");
        photoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                photoMenuActionPerformed(evt);
            }
        });
        newMenu.add(photoMenu);

        documentMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        documentMenu.setText("document");
        documentMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                documentMenuActionPerformed(evt);
            }
        });
        newMenu.add(documentMenu);

        jMenu12.add(newMenu);

        openMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        openMenu.setText("open");
        openMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuActionPerformed(evt);
            }
        });
        jMenu12.add(openMenu);

        aboutMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ENTER, java.awt.event.InputEvent.ALT_MASK));
        aboutMenu.setText("about us");
        aboutMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuActionPerformed(evt);
            }
        });
        jMenu12.add(aboutMenu);

        exitMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        exitMenu.setText("exit");
        exitMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuActionPerformed(evt);
            }
        });
        jMenu12.add(exitMenu);

        jMenuBar1.add(jMenu12);

        jMenu2.setText("Account");

        signInMenu.setText("sign in");
        signInMenu.setToolTipText("Your account must have been created . Signing in to your account requires username and password . ");
        signInMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signInMenuActionPerformed(evt);
            }
        });
        jMenu2.add(signInMenu);

        signUpMenu.setText("sign up");
        signUpMenu.setToolTipText("You need to create an account before using this application");
        signUpMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpMenuActionPerformed(evt);
            }
        });
        jMenu2.add(signUpMenu);

        signOutMenu.setText("sign out");
        signOutMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signOutMenuActionPerformed(evt);
            }
        });
        jMenu2.add(signOutMenu);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>

    private void openMenuActionPerformed(java.awt.event.ActionEvent evt) {
        if(accountstatus ==true) {
            OpenWindow OW = new OpenWindow();
            OW.setVisible(true);
            OW.setResizable(false);
            accountstatus = OW.status();
            checkAccount();
        }
        else
            JOptionPane.showMessageDialog(null , "you must be Signed in first ");
    }

    private void jMenu12ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void aboutMenuActionPerformed(java.awt.event.ActionEvent evt) {
        JOptionPane.showMessageDialog(null , "This application is designed by Randkill & JamalP\nfor contacting me please mail to erfan.vh@gmail.com" );
    }

    private void exitMenuActionPerformed(java.awt.event.ActionEvent evt) {
        System.exit( 0);
    }

    private void signInMenuActionPerformed(java.awt.event.ActionEvent evt) {
        SignInPage signinpage = new SignInPage();
        signinpage.setVisible(true);
        signinpage.setResizable(false);
        //signinpage.getData();
        accountstatus =signinpage.status();

        checkAccount();
    }

    private void signUpMenuActionPerformed(java.awt.event.ActionEvent evt) {
        SignUpPage signuppage = new SignUpPage();
        signuppage.setVisible(true);
        signuppage.setResizable(false);
    }

    private void signOutMenuActionPerformed(java.awt.event.ActionEvent evt) {
        accountstatus = false;
        checkAccount();
    }

    private void audioMenuActionPerformed(java.awt.event.ActionEvent evt) {
        if(accountstatus ==true) {
            AudioWindow AW = new AudioWindow();
            AW.setVisible(true);
            AW.setResizable(false);
            accountstatus = AW.status();
        }
        else
            JOptionPane.showMessageDialog(null , "you must be Signed in first ");
    }

    private void photoMenuActionPerformed(java.awt.event.ActionEvent evt) {
        if(accountstatus ==true) {
            PhotoWindows PW = new PhotoWindows();
            PW.setVisible(true);
            PW.setResizable(false);
            accountstatus = PW.status();
        }
        else
            JOptionPane.showMessageDialog(null , "you must be Signed in first ");
    }

    private void documentMenuActionPerformed(java.awt.event.ActionEvent evt) {
        if(accountstatus ==true) {
            EbookWindow EW = new EbookWindow();
            EW.setVisible(true);
            EW.setResizable(false);
            accountstatus = EW.status();
        }
        else
            JOptionPane.showMessageDialog(null , "you must be Signed in first ");
    }

    private void videoMenuActionPerformed(java.awt.event.ActionEvent evt) {
        if(accountstatus ==true) {
            VideoWindow VW = new VideoWindow();
            VW.setVisible(true);
            VW.setResizable(false);
            accountstatus = VW.status();
        }
        else
            JOptionPane.showMessageDialog(null , "you must be Signed in first ");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WelcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WelcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WelcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WelcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WelcomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JMenuItem aboutMenu;
    private javax.swing.JMenuItem audioMenu;
    private javax.swing.JMenuItem documentMenu;
    private javax.swing.JMenuItem exitMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu newMenu;
    private javax.swing.JMenuItem openMenu;
    private javax.swing.JMenuItem photoMenu;
    private javax.swing.JMenuItem saveMenu;
    private javax.swing.JMenuItem signInMenu;
    private javax.swing.JMenuItem signOutMenu;
    private javax.swing.JMenuItem signUpMenu;
    private javax.swing.JMenuItem videoMenu;
    private javax.swing.JLabel Signedin;
    private javax.swing.JLabel nSignedin;
    // End of variables declaration
}
